"""Leakage-safe ML datasets and the uncalibrated TASK 16 baseline."""

from pitchvalue.ml.calibration import (
    CalibratedMLPrediction,
    CalibrationFitExample,
    CalibrationStatus,
    FittedTemperatureCalibrator,
    TemperatureScalingConfig,
    apply_temperature_scaling,
    fit_temperature_scaling,
)
from pitchvalue.ml.calibration_evaluation import (
    CalibrationCandidateDecision,
    CalibrationEvaluationResult,
    ClassCalibrationComparison,
    FoldCalibrationResult,
    NestedCalibrationConfig,
    SliceCalibrationResult,
    evaluate_nested_temperature_scaling,
)
from pitchvalue.ml.config import (
    DatasetBuilderConfig,
    FeatureProfile,
    FeatureSchema,
    MissingValuePolicy,
    MLDatasetValidationError,
    MLTrainingConfig,
    PreprocessingPolicy,
)
from pitchvalue.ml.contracts import (
    DatasetDiagnostic,
    DatasetStatus,
    DiagnosticCode,
    FeatureKind,
    FeatureRecord,
    MarketFeatureSemantics,
    MissingReason,
    MLDataset,
    RejectedTrainingRow,
    ResolvedMatchOutcome,
    RowStatus,
    TargetDefinition,
    TargetMode,
    TrainingCandidate,
    TrainingRow,
)
from pitchvalue.ml.dataset import build_dataset
from pitchvalue.ml.evaluation import MLEvaluationResult, evaluate_walk_forward_ml
from pitchvalue.ml.features import order_features
from pitchvalue.ml.model import (
    ML_CLASS_ORDER,
    FittedMultinomialLogistic,
    MLClassProbability,
    MLModelStatus,
    MLPrediction,
    fit_multinomial_logistic,
    predict_multinomial_logistic,
)
from pitchvalue.ml.preprocessing import FittedPreprocessor, fit_preprocessor, transform_rows
from pitchvalue.ml.provenance import (
    DatasetRowProvenance,
    FeatureProvenance,
    SourceMatchReference,
)
from pitchvalue.ml.targets import TargetDerivation, derive_target
from pitchvalue.ml.validation import validate_candidate

__all__ = [
    "CalibratedMLPrediction",
    "CalibrationCandidateDecision",
    "CalibrationEvaluationResult",
    "CalibrationFitExample",
    "CalibrationStatus",
    "ClassCalibrationComparison",
    "DatasetBuilderConfig",
    "DatasetDiagnostic",
    "DatasetRowProvenance",
    "DatasetStatus",
    "DiagnosticCode",
    "FeatureKind",
    "FeatureProfile",
    "FeatureProvenance",
    "FeatureRecord",
    "FeatureSchema",
    "FittedMultinomialLogistic",
    "FittedPreprocessor",
    "FittedTemperatureCalibrator",
    "FoldCalibrationResult",
    "MarketFeatureSemantics",
    "MLDataset",
    "MLDatasetValidationError",
    "MLEvaluationResult",
    "MLTrainingConfig",
    "MLClassProbability",
    "MLModelStatus",
    "MLPrediction",
    "ML_CLASS_ORDER",
    "MissingReason",
    "MissingValuePolicy",
    "NestedCalibrationConfig",
    "PreprocessingPolicy",
    "RejectedTrainingRow",
    "ResolvedMatchOutcome",
    "RowStatus",
    "SourceMatchReference",
    "SliceCalibrationResult",
    "TargetDefinition",
    "TargetDerivation",
    "TargetMode",
    "TrainingCandidate",
    "TrainingRow",
    "TemperatureScalingConfig",
    "apply_temperature_scaling",
    "build_dataset",
    "derive_target",
    "evaluate_walk_forward_ml",
    "evaluate_nested_temperature_scaling",
    "fit_multinomial_logistic",
    "fit_preprocessor",
    "fit_temperature_scaling",
    "order_features",
    "predict_multinomial_logistic",
    "transform_rows",
    "validate_candidate",
]
