"""Create the football-data.co.uk staging foundation.

Revision ID: 20260908_0004
Revises: 20260907_0003
Create Date: 2026-09-08 00:00:00
"""

from collections.abc import Sequence

from alembic import op

revision: str = "20260908_0004"
down_revision: str | None = "20260907_0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create provider-owned staging without changing canonical football tables."""
    op.execute(
        """
        CREATE TABLE football_data_staging_rows (
            staging_row_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            import_batch_id bigint NOT NULL REFERENCES import_batches (import_batch_id)
                ON DELETE RESTRICT,
            source_row_number integer NOT NULL CHECK (source_row_number > 0),
            competition_source_code text NOT NULL
                CHECK (length(btrim(competition_source_code)) > 0),
            season_name text NOT NULL CHECK (length(btrim(season_name)) > 0),
            raw_row jsonb NOT NULL,
            row_hash char(64) NOT NULL CHECK (row_hash ~ '^[0-9a-f]{64}$'),
            parsing_status text NOT NULL CHECK (parsing_status IN ('parsed', 'rejected')),
            rejection_reason text,
            created_at timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT uq_football_data_staging_batch_row
                UNIQUE (import_batch_id, source_row_number),
            CONSTRAINT ck_football_data_staging_rejection CHECK (
                (parsing_status = 'parsed' AND rejection_reason IS NULL)
                OR (
                    parsing_status = 'rejected'
                    AND length(btrim(rejection_reason)) > 0
                )
            )
        );

        COMMENT ON TABLE football_data_staging_rows IS
            'Provider-owned football-data.co.uk staging rows; not canonical football data';

        CREATE INDEX ix_football_data_staging_batch_status
            ON football_data_staging_rows (import_batch_id, parsing_status);
        CREATE INDEX ix_football_data_staging_row_hash
            ON football_data_staging_rows (row_hash);
        """
    )


def downgrade() -> None:
    """Remove only the football-data.co.uk staging table."""
    op.execute("DROP TABLE football_data_staging_rows;")
