"""Create the canonical football database foundation.

Revision ID: 20260907_0002
Revises: 20260907_0001
Create Date: 2026-09-07 01:00:00
"""

from collections.abc import Sequence

from alembic import op

revision: str = "20260907_0002"
down_revision: str | None = "20260907_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create canonical tables, constraints, indexes, and reference competitions."""
    op.execute(
        """
        CREATE TABLE providers (
            provider_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name text NOT NULL UNIQUE CHECK (btrim(name) <> ''),
            provider_type text NOT NULL CHECK (btrim(provider_type) <> ''),
            base_url text,
            license_type text,
            priority integer NOT NULL CHECK (priority > 0),
            active boolean NOT NULL DEFAULT true,
            created_at timestamptz NOT NULL DEFAULT now(),
            updated_at timestamptz NOT NULL DEFAULT now()
        );

        CREATE TABLE competitions (
            competition_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            canonical_name text NOT NULL CHECK (btrim(canonical_name) <> ''),
            country_code varchar(3),
            competition_type text NOT NULL CHECK (
                competition_type IN ('domestic_league', 'domestic_cup', 'continental_club')
            ),
            gender text NOT NULL DEFAULT 'men' CHECK (btrim(gender) <> ''),
            active boolean NOT NULL DEFAULT true,
            created_at timestamptz NOT NULL DEFAULT now(),
            updated_at timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT uq_competitions_name_gender UNIQUE (canonical_name, gender),
            CONSTRAINT ck_competitions_country_code CHECK (
                country_code IS NULL OR country_code ~ '^[A-Z]{3}$'
            )
        );

        CREATE TABLE competition_provider_refs (
            competition_provider_ref_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            competition_id bigint NOT NULL REFERENCES competitions (competition_id)
                ON DELETE RESTRICT,
            provider_id bigint NOT NULL REFERENCES providers (provider_id) ON DELETE RESTRICT,
            provider_competition_id text,
            provider_name text,
            provider_code text,
            created_at timestamptz NOT NULL DEFAULT now(),
            updated_at timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT ck_competition_provider_ref_present CHECK (
                NULLIF(btrim(provider_competition_id), '') IS NOT NULL
                OR NULLIF(btrim(provider_name), '') IS NOT NULL
                OR NULLIF(btrim(provider_code), '') IS NOT NULL
            )
        );

        CREATE UNIQUE INDEX uq_competition_provider_external_id
            ON competition_provider_refs (provider_id, provider_competition_id)
            WHERE provider_competition_id IS NOT NULL;

        CREATE TABLE seasons (
            season_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            competition_id bigint NOT NULL REFERENCES competitions (competition_id)
                ON DELETE RESTRICT,
            season_name text NOT NULL CHECK (btrim(season_name) <> ''),
            start_year integer NOT NULL,
            end_year integer NOT NULL,
            start_date date,
            end_date date,
            status text NOT NULL CHECK (btrim(status) <> ''),
            created_at timestamptz NOT NULL DEFAULT now(),
            updated_at timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT uq_seasons_competition_name UNIQUE (competition_id, season_name),
            CONSTRAINT uq_seasons_id_competition UNIQUE (season_id, competition_id),
            CONSTRAINT ck_seasons_years CHECK (end_year >= start_year),
            CONSTRAINT ck_seasons_dates CHECK (
                start_date IS NULL OR end_date IS NULL OR end_date >= start_date
            )
        );

        CREATE TABLE teams (
            team_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            canonical_name text NOT NULL CHECK (btrim(canonical_name) <> ''),
            normalized_name text NOT NULL CHECK (btrim(normalized_name) <> ''),
            country_code varchar(3),
            active boolean NOT NULL DEFAULT true,
            created_at timestamptz NOT NULL DEFAULT now(),
            updated_at timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT ck_teams_country_code CHECK (
                country_code IS NULL OR country_code ~ '^[A-Z]{3}$'
            )
        );

        CREATE INDEX ix_teams_normalized_name ON teams (normalized_name);

        CREATE TABLE team_aliases (
            team_alias_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            team_id bigint NOT NULL REFERENCES teams (team_id) ON DELETE RESTRICT,
            provider_id bigint REFERENCES providers (provider_id) ON DELETE RESTRICT,
            alias text NOT NULL CHECK (btrim(alias) <> ''),
            normalized_alias text NOT NULL CHECK (btrim(normalized_alias) <> ''),
            provider_team_id text,
            valid_from date,
            valid_to date,
            created_at timestamptz NOT NULL DEFAULT now(),
            updated_at timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT ck_team_alias_dates CHECK (
                valid_from IS NULL OR valid_to IS NULL OR valid_to >= valid_from
            ),
            CONSTRAINT ck_team_alias_provider_context CHECK (
                provider_team_id IS NULL OR provider_id IS NOT NULL
            )
        );

        CREATE INDEX ix_team_aliases_normalized_alias ON team_aliases (normalized_alias);
        CREATE UNIQUE INDEX uq_team_aliases_provider_team_id
            ON team_aliases (provider_id, provider_team_id)
            WHERE provider_team_id IS NOT NULL;

        CREATE TABLE matches (
            match_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            competition_id bigint NOT NULL REFERENCES competitions (competition_id)
                ON DELETE RESTRICT,
            season_id bigint NOT NULL,
            stage text,
            round text,
            matchday integer CHECK (matchday IS NULL OR matchday > 0),
            leg smallint CHECK (leg IS NULL OR leg IN (1, 2)),
            kickoff_at_utc timestamptz,
            kickoff_timezone text,
            home_team_id bigint NOT NULL REFERENCES teams (team_id) ON DELETE RESTRICT,
            away_team_id bigint NOT NULL REFERENCES teams (team_id) ON DELETE RESTRICT,
            status text NOT NULL CHECK (
                status IN ('SCHEDULED', 'FINISHED', 'AWARDED', 'ABANDONED',
                           'POSTPONED', 'CANCELLED')
            ),
            home_score integer,
            away_score integer,
            home_ht_score integer,
            away_ht_score integer,
            home_extra_time_score integer,
            away_extra_time_score integer,
            home_penalty_score integer,
            away_penalty_score integer,
            result varchar(1) CHECK (result IS NULL OR result IN ('H', 'D', 'A')),
            decided_by text CHECK (
                decided_by IS NULL
                OR decided_by IN ('regular_time', 'extra_time', 'penalties', 'awarded')
            ),
            score_is_awarded boolean NOT NULL DEFAULT false,
            venue text,
            referee text,
            created_at timestamptz NOT NULL DEFAULT now(),
            updated_at timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT fk_matches_season_competition
                FOREIGN KEY (season_id, competition_id)
                REFERENCES seasons (season_id, competition_id) ON DELETE RESTRICT,
            CONSTRAINT ck_matches_distinct_teams CHECK (home_team_id <> away_team_id),
            CONSTRAINT ck_matches_scores_nonnegative CHECK (
                (home_score IS NULL OR home_score >= 0)
                AND (away_score IS NULL OR away_score >= 0)
                AND (home_ht_score IS NULL OR home_ht_score >= 0)
                AND (away_ht_score IS NULL OR away_ht_score >= 0)
                AND (home_extra_time_score IS NULL OR home_extra_time_score >= 0)
                AND (away_extra_time_score IS NULL OR away_extra_time_score >= 0)
                AND (home_penalty_score IS NULL OR home_penalty_score >= 0)
                AND (away_penalty_score IS NULL OR away_penalty_score >= 0)
            ),
            CONSTRAINT ck_matches_score_pairs CHECK (
                ((home_score IS NULL) = (away_score IS NULL))
                AND ((home_ht_score IS NULL) = (away_ht_score IS NULL))
                AND ((home_extra_time_score IS NULL) = (away_extra_time_score IS NULL))
                AND ((home_penalty_score IS NULL) = (away_penalty_score IS NULL))
            ),
            CONSTRAINT ck_matches_finished_result CHECK (
                status <> 'FINISHED'
                OR (home_score IS NOT NULL AND away_score IS NOT NULL AND result IS NOT NULL)
            ),
            CONSTRAINT ck_matches_awarded_result CHECK (
                status <> 'AWARDED' OR result IS NOT NULL
            )
        );

        CREATE INDEX ix_matches_kickoff_at_utc ON matches (kickoff_at_utc);
        CREATE INDEX ix_matches_competition_season ON matches (competition_id, season_id);
        CREATE INDEX ix_matches_home_team ON matches (home_team_id);
        CREATE INDEX ix_matches_away_team ON matches (away_team_id);
        CREATE INDEX ix_matches_reconciliation_candidate
            ON matches (
                competition_id, season_id, home_team_id, away_team_id, kickoff_at_utc
            );

        CREATE TABLE match_provider_refs (
            match_provider_ref_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            match_id bigint NOT NULL REFERENCES matches (match_id) ON DELETE RESTRICT,
            provider_id bigint NOT NULL REFERENCES providers (provider_id) ON DELETE RESTRICT,
            provider_match_id text,
            source_url text,
            source_record_hash text,
            created_at timestamptz NOT NULL DEFAULT now(),
            updated_at timestamptz NOT NULL DEFAULT now()
        );

        CREATE UNIQUE INDEX uq_match_provider_external_id
            ON match_provider_refs (provider_id, provider_match_id)
            WHERE provider_match_id IS NOT NULL;
        CREATE INDEX ix_match_provider_refs_match ON match_provider_refs (match_id);
        CREATE INDEX ix_match_provider_refs_source_hash
            ON match_provider_refs (source_record_hash)
            WHERE source_record_hash IS NOT NULL;

        CREATE TABLE match_statistics (
            match_statistics_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            match_id bigint NOT NULL REFERENCES matches (match_id) ON DELETE RESTRICT,
            provider_id bigint REFERENCES providers (provider_id) ON DELETE RESTRICT,
            home_shots integer,
            home_shots_on_target integer,
            home_possession numeric(5, 2),
            home_corners integer,
            home_fouls integer,
            home_yellow_cards integer,
            home_red_cards integer,
            home_xg numeric(6, 3),
            away_shots integer,
            away_shots_on_target integer,
            away_possession numeric(5, 2),
            away_corners integer,
            away_fouls integer,
            away_yellow_cards integer,
            away_red_cards integer,
            away_xg numeric(6, 3),
            created_at timestamptz NOT NULL DEFAULT now(),
            updated_at timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT uq_match_statistics_match_provider
                UNIQUE NULLS NOT DISTINCT (match_id, provider_id),
            CONSTRAINT ck_match_statistics_counts_nonnegative CHECK (
                (home_shots IS NULL OR home_shots >= 0)
                AND (home_shots_on_target IS NULL OR home_shots_on_target >= 0)
                AND (home_corners IS NULL OR home_corners >= 0)
                AND (home_fouls IS NULL OR home_fouls >= 0)
                AND (home_yellow_cards IS NULL OR home_yellow_cards >= 0)
                AND (home_red_cards IS NULL OR home_red_cards >= 0)
                AND (away_shots IS NULL OR away_shots >= 0)
                AND (away_shots_on_target IS NULL OR away_shots_on_target >= 0)
                AND (away_corners IS NULL OR away_corners >= 0)
                AND (away_fouls IS NULL OR away_fouls >= 0)
                AND (away_yellow_cards IS NULL OR away_yellow_cards >= 0)
                AND (away_red_cards IS NULL OR away_red_cards >= 0)
            ),
            CONSTRAINT ck_match_statistics_possession_range CHECK (
                (home_possession IS NULL OR home_possession BETWEEN 0 AND 100)
                AND (away_possession IS NULL OR away_possession BETWEEN 0 AND 100)
            ),
            CONSTRAINT ck_match_statistics_xg_nonnegative CHECK (
                (home_xg IS NULL OR home_xg >= 0)
                AND (away_xg IS NULL OR away_xg >= 0)
            )
        );

        CREATE INDEX ix_match_statistics_match ON match_statistics (match_id);

        CREATE TABLE odds_snapshots (
            odds_snapshot_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            match_id bigint NOT NULL REFERENCES matches (match_id) ON DELETE RESTRICT,
            provider_id bigint REFERENCES providers (provider_id) ON DELETE RESTRICT,
            bookmaker text NOT NULL CHECK (btrim(bookmaker) <> ''),
            market text NOT NULL CHECK (btrim(market) <> ''),
            selection text NOT NULL CHECK (btrim(selection) <> ''),
            line numeric(8, 3),
            decimal_odds numeric(10, 4) NOT NULL CHECK (decimal_odds > 1.0),
            snapshot_at timestamptz,
            snapshot_type text NOT NULL CHECK (
                snapshot_type IN (
                    'opening', 'morning', 'lineup', 't_minus_15', 'closing', 'unknown'
                )
            ),
            provider_market_id text,
            created_at timestamptz NOT NULL DEFAULT now()
        );

        CREATE INDEX ix_odds_snapshots_lookup
            ON odds_snapshots (
                match_id, market, bookmaker, snapshot_type, snapshot_at
            );

        CREATE TABLE data_quality (
            match_id bigint PRIMARY KEY REFERENCES matches (match_id) ON DELETE RESTRICT,
            result_available boolean NOT NULL DEFAULT false,
            stats_available boolean NOT NULL DEFAULT false,
            odds_available boolean NOT NULL DEFAULT false,
            xg_available boolean NOT NULL DEFAULT false,
            lineup_available boolean NOT NULL DEFAULT false,
            injury_available boolean NOT NULL DEFAULT false,
            result_verified boolean NOT NULL DEFAULT false,
            cross_provider_verified boolean NOT NULL DEFAULT false,
            quality_score numeric(5, 2),
            quality_flags jsonb,
            last_validated_at timestamptz,
            created_at timestamptz NOT NULL DEFAULT now(),
            updated_at timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT ck_data_quality_score CHECK (
                quality_score IS NULL OR quality_score BETWEEN 0 AND 100
            )
        );

        CREATE TABLE import_batches (
            import_batch_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            provider_id bigint NOT NULL REFERENCES providers (provider_id) ON DELETE RESTRICT,
            started_at timestamptz NOT NULL,
            completed_at timestamptz,
            source_identifier text NOT NULL CHECK (btrim(source_identifier) <> ''),
            source_hash text,
            rows_read integer NOT NULL DEFAULT 0 CHECK (rows_read >= 0),
            rows_inserted integer NOT NULL DEFAULT 0 CHECK (rows_inserted >= 0),
            rows_updated integer NOT NULL DEFAULT 0 CHECK (rows_updated >= 0),
            rows_rejected integer NOT NULL DEFAULT 0 CHECK (rows_rejected >= 0),
            status text NOT NULL CHECK (
                status IN ('running', 'completed', 'completed_with_errors', 'failed')
            ),
            error_summary text,
            created_at timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT ck_import_batches_completion CHECK (
                completed_at IS NULL OR completed_at >= started_at
            )
        );

        INSERT INTO competitions (
            canonical_name, country_code, competition_type, gender
        ) VALUES
            ('Premier League', 'ENG', 'domestic_league', 'men'),
            ('Ligue 1', 'FRA', 'domestic_league', 'men'),
            ('Bundesliga', 'DEU', 'domestic_league', 'men'),
            ('Süper Lig', 'TUR', 'domestic_league', 'men'),
            ('Primeira Liga', 'PRT', 'domestic_league', 'men'),
            ('La Liga', 'ESP', 'domestic_league', 'men'),
            ('Scottish Premiership', 'SCO', 'domestic_league', 'men'),
            ('UEFA Champions League', NULL, 'continental_club', 'men'),
            ('UEFA Europa League', NULL, 'continental_club', 'men'),
            ('UEFA Conference League', NULL, 'continental_club', 'men')
        ON CONFLICT (canonical_name, gender) DO NOTHING;
        """
    )


def downgrade() -> None:
    """Remove the canonical schema in reverse dependency order."""
    op.execute(
        """
        DROP TABLE import_batches;
        DROP TABLE data_quality;
        DROP TABLE odds_snapshots;
        DROP TABLE match_statistics;
        DROP TABLE match_provider_refs;
        DROP TABLE matches;
        DROP TABLE team_aliases;
        DROP TABLE teams;
        DROP TABLE seasons;
        DROP TABLE competition_provider_refs;
        DROP TABLE competitions;
        DROP TABLE providers;
        """
    )
