"""Add provider-neutral current-season and internal shadow persistence.

Revision ID: 20260913_0011
Revises: 20260912_0010
Create Date: 2026-09-13 08:00:00
"""

from collections.abc import Sequence

from alembic import op

revision: str = "20260913_0011"
down_revision: str | None = "20260912_0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create replay-safe source identity and non-public shadow evidence."""
    op.execute(
        """
        CREATE TABLE source_entity_references (
            source_entity_ref_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            provider_id bigint NOT NULL REFERENCES providers (provider_id) ON DELETE RESTRICT,
            entity_type text NOT NULL CHECK (entity_type IN ('COMPETITION', 'TEAM', 'FIXTURE')),
            provider_entity_id text NOT NULL CHECK (length(btrim(provider_entity_id)) > 0),
            provider_display_name text NOT NULL CHECK (length(btrim(provider_display_name)) > 0),
            canonical_competition_id bigint REFERENCES competitions (competition_id)
                ON DELETE RESTRICT,
            canonical_team_id bigint REFERENCES teams (team_id) ON DELETE RESTRICT,
            canonical_match_id bigint REFERENCES matches (match_id) ON DELETE RESTRICT,
            mapping_status text NOT NULL CHECK (mapping_status IN (
                'RESOLVED', 'UNRESOLVED', 'REVIEW_REQUIRED', 'CONFLICT', 'UNSUPPORTED'
            )),
            mapping_version text NOT NULL CHECK (length(btrim(mapping_version)) > 0),
            provenance text NOT NULL CHECK (length(btrim(provenance)) > 0),
            source_payload_hash varchar(64) CHECK (
                source_payload_hash IS NULL OR source_payload_hash ~ '^[0-9a-f]{64}$'
            ),
            first_seen_at timestamptz NOT NULL,
            last_seen_at timestamptz NOT NULL,
            CONSTRAINT uq_source_entity_identity UNIQUE (
                provider_id, entity_type, provider_entity_id
            ),
            CONSTRAINT ck_source_entity_seen_order CHECK (last_seen_at >= first_seen_at),
            CONSTRAINT ck_source_entity_target_shape CHECK (
                (entity_type = 'COMPETITION' AND canonical_team_id IS NULL
                    AND canonical_match_id IS NULL)
                OR (entity_type = 'TEAM' AND canonical_competition_id IS NULL
                    AND canonical_match_id IS NULL)
                OR (entity_type = 'FIXTURE' AND canonical_competition_id IS NULL
                    AND canonical_team_id IS NULL)
            ),
            CONSTRAINT ck_source_entity_resolved_target CHECK (
                mapping_status <> 'RESOLVED'
                OR (entity_type = 'COMPETITION' AND canonical_competition_id IS NOT NULL)
                OR (entity_type = 'TEAM' AND canonical_team_id IS NOT NULL)
                OR (entity_type = 'FIXTURE' AND canonical_match_id IS NOT NULL)
            )
        );

        ALTER TABLE engine_runs
            ADD COLUMN provider_id bigint REFERENCES providers (provider_id) ON DELETE RESTRICT;

        ALTER TABLE run_quarantines
            ALTER COLUMN match_id DROP NOT NULL,
            ADD COLUMN source_entity_ref_id bigint REFERENCES source_entity_references
                (source_entity_ref_id) ON DELETE RESTRICT,
            ADD CONSTRAINT ck_run_quarantine_identity CHECK (
                (match_id IS NOT NULL)::integer +
                (source_entity_ref_id IS NOT NULL)::integer = 1
            );

        CREATE TABLE shadow_analysis_snapshots (
            shadow_analysis_id varchar(64) PRIMARY KEY CHECK (
                shadow_analysis_id ~ '^[0-9a-f]{64}$'
            ),
            run_id text NOT NULL REFERENCES engine_runs (run_id) ON DELETE RESTRICT,
            match_id bigint NOT NULL REFERENCES matches (match_id) ON DELETE RESTRICT,
            prediction_as_of timestamptz NOT NULL,
            model_version text NOT NULL CHECK (length(btrim(model_version)) > 0),
            feature_version text NOT NULL CHECK (length(btrim(feature_version)) > 0),
            raw_ml_probabilities jsonb NOT NULL CHECK (
                jsonb_typeof(raw_ml_probabilities) = 'object'
            ),
            elo_output jsonb,
            poisson_output jsonb,
            form_output jsonb,
            agreement_output jsonb,
            odds_mode text NOT NULL CHECK (odds_mode IN (
                'MODEL_ONLY', 'MARKET_REFERENCE_ONLY', 'EXACT_TIME_MARKET'
            )),
            dq_state text NOT NULL CHECK (length(btrim(dq_state)) > 0),
            market_stability text NOT NULL CHECK (length(btrim(market_stability)) > 0),
            calibration_confidence text NOT NULL CHECK (
                length(btrim(calibration_confidence)) > 0
            ),
            bet_score numeric CHECK (bet_score IS NULL OR bet_score BETWEEN 0 AND 100),
            bet_score_completeness text NOT NULL CHECK (
                bet_score_completeness IN ('COMPLETE', 'PARTIAL', 'UNAVAILABLE')
            ),
            publication_eligible boolean NOT NULL DEFAULT false CHECK (
                publication_eligible = false
            ),
            diagnostics text[] NOT NULL DEFAULT ARRAY[]::text[],
            payload_hash varchar(64) NOT NULL CHECK (payload_hash ~ '^[0-9a-f]{64}$'),
            persisted_at timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT uq_shadow_run_match UNIQUE (run_id, match_id)
        );

        CREATE UNIQUE INDEX uq_live_odds_provider_market_version
            ON odds_snapshots (provider_id, provider_market_id, normalization_version)
            WHERE observation_origin = 'live_source'
              AND provider_id IS NOT NULL
              AND provider_market_id IS NOT NULL
              AND normalization_version IS NOT NULL;

        CREATE INDEX ix_source_entity_mapping_queue
            ON source_entity_references (provider_id, entity_type, mapping_status);
        CREATE INDEX ix_shadow_analysis_run
            ON shadow_analysis_snapshots (run_id, match_id);

        COMMENT ON TABLE source_entity_references IS
            'Provider-neutral external identity and explicit mapping review queue';
        COMMENT ON TABLE shadow_analysis_snapshots IS
            'Internal-only shadow evidence; publication is prohibited by database constraint';
        """
    )


def downgrade() -> None:
    """Remove only current-season/shadow persistence additions."""
    op.execute(
        """
        DROP INDEX uq_live_odds_provider_market_version;
        DROP TABLE shadow_analysis_snapshots;
        ALTER TABLE run_quarantines
            DROP CONSTRAINT ck_run_quarantine_identity,
            DROP COLUMN source_entity_ref_id,
            ALTER COLUMN match_id SET NOT NULL;
        ALTER TABLE engine_runs DROP COLUMN provider_id;
        DROP TABLE source_entity_references;
        """
    )
