"""Create explicit football-data.co.uk canonical import lineage.

Revision ID: 20260908_0005
Revises: 20260908_0004
Create Date: 2026-09-08 01:00:00
"""

from collections.abc import Sequence

from alembic import op

revision: str = "20260908_0005"
down_revision: str | None = "20260908_0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Link each staged source row to its resolved canonical match."""
    op.execute(
        """
        CREATE TABLE football_data_canonical_lineage (
            football_data_lineage_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            staging_row_id bigint NOT NULL UNIQUE
                REFERENCES football_data_staging_rows (staging_row_id) ON DELETE RESTRICT,
            match_id bigint NOT NULL REFERENCES matches (match_id) ON DELETE RESTRICT,
            created_at timestamptz NOT NULL DEFAULT now()
        );

        COMMENT ON TABLE football_data_canonical_lineage IS
            'Provider-owned lineage from a staged football-data.co.uk row to a canonical match';

        CREATE INDEX ix_football_data_lineage_match
            ON football_data_canonical_lineage (match_id);
        """
    )


def downgrade() -> None:
    """Remove only football-data.co.uk canonical lineage."""
    op.execute("DROP TABLE football_data_canonical_lineage;")
