"""Add provider-neutral product service persistence.

Revision ID: 20260916_0012
Revises: 20260913_0011
Create Date: 2026-09-16 12:00:00
"""

from collections.abc import Sequence

from alembic import op

revision: str = "20260916_0012"
down_revision: str | None = "20260913_0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create user-scoped services without changing global prediction identity."""
    op.execute(
        """
        CREATE TABLE app_users (
            user_id varchar(36) PRIMARY KEY,
            account_kind text NOT NULL CHECK (account_kind IN ('GUEST', 'AUTHENTICATED')),
            status text NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'DISABLED')),
            created_at timestamptz NOT NULL,
            updated_at timestamptz NOT NULL,
            CONSTRAINT ck_app_user_updated CHECK (updated_at >= created_at)
        );

        CREATE TABLE auth_identities (
            auth_identity_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id varchar(36) NOT NULL REFERENCES app_users (user_id) ON DELETE RESTRICT,
            provider text NOT NULL CHECK (provider IN ('GUEST', 'EMAIL', 'APPLE', 'GOOGLE')),
            provider_subject text NOT NULL CHECK (length(btrim(provider_subject)) > 0),
            normalized_email text,
            password_hash text,
            created_at timestamptz NOT NULL,
            last_verified_at timestamptz,
            CONSTRAINT uq_auth_provider_subject UNIQUE (provider, provider_subject),
            CONSTRAINT ck_email_identity_shape CHECK (
                (provider = 'EMAIL' AND normalized_email IS NOT NULL AND password_hash IS NOT NULL)
                OR (provider <> 'EMAIL' AND password_hash IS NULL)
            )
        );
        CREATE UNIQUE INDEX uq_auth_normalized_email
            ON auth_identities (normalized_email) WHERE normalized_email IS NOT NULL;

        CREATE TABLE auth_sessions (
            session_id varchar(36) PRIMARY KEY,
            user_id varchar(36) NOT NULL REFERENCES app_users (user_id) ON DELETE RESTRICT,
            access_token_hash varchar(64) NOT NULL UNIQUE CHECK (
                access_token_hash ~ '^[0-9a-f]{64}$'
            ),
            refresh_token_hash varchar(64) NOT NULL UNIQUE CHECK (
                refresh_token_hash ~ '^[0-9a-f]{64}$'
            ),
            issued_at timestamptz NOT NULL,
            access_expires_at timestamptz NOT NULL,
            refresh_expires_at timestamptz NOT NULL,
            revoked_at timestamptz,
            replaced_by_session_id varchar(36) REFERENCES auth_sessions (session_id)
                ON DELETE RESTRICT,
            CONSTRAINT ck_auth_session_expiry CHECK (
                access_expires_at > issued_at AND refresh_expires_at > access_expires_at
            )
        );
        CREATE INDEX ix_auth_sessions_user_active
            ON auth_sessions (user_id, refresh_expires_at DESC) WHERE revoked_at IS NULL;

        CREATE TABLE entitlement_evidence (
            entitlement_evidence_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id varchar(36) NOT NULL REFERENCES app_users (user_id) ON DELETE RESTRICT,
            state text NOT NULL CHECK (state IN (
                'GUEST', 'PREMIUM_ACTIVE', 'PREMIUM_TRIAL',
                'PREMIUM_EXPIRED', 'PREMIUM_INACTIVE'
            )),
            source text NOT NULL CHECK (length(btrim(source)) > 0),
            product_identifier text,
            external_reference text NOT NULL CHECK (length(btrim(external_reference)) > 0),
            starts_at timestamptz NOT NULL,
            ends_at timestamptz,
            trial boolean NOT NULL DEFAULT false,
            auto_renewing boolean,
            cancellation_at timestamptz,
            reconciled_at timestamptz NOT NULL,
            payload_hash varchar(64) NOT NULL CHECK (payload_hash ~ '^[0-9a-f]{64}$'),
            CONSTRAINT uq_entitlement_source_reference UNIQUE (source, external_reference),
            CONSTRAINT ck_entitlement_period CHECK (ends_at IS NULL OR ends_at > starts_at),
            CONSTRAINT ck_trial_state CHECK (trial = false OR state = 'PREMIUM_TRIAL')
        );
        CREATE INDEX ix_entitlement_user_current
            ON entitlement_evidence (user_id, reconciled_at DESC, entitlement_evidence_id DESC);

        CREATE TABLE commerce_evidence (
            commerce_evidence_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id varchar(36) NOT NULL REFERENCES app_users (user_id) ON DELETE RESTRICT,
            provider text NOT NULL CHECK (length(btrim(provider)) > 0),
            external_transaction_id text NOT NULL CHECK (
                length(btrim(external_transaction_id)) > 0
            ),
            product_identifier text NOT NULL CHECK (length(btrim(product_identifier)) > 0),
            plan text NOT NULL CHECK (plan IN ('MONTHLY', 'THREE_MONTH', 'ANNUAL')),
            verification_state text NOT NULL CHECK (verification_state IN (
                'VERIFIED', 'EXPIRED', 'CANCELLED', 'GRACE', 'REJECTED'
            )),
            purchased_at timestamptz,
            expires_at timestamptz,
            trial_eligible boolean,
            is_trial boolean NOT NULL DEFAULT false,
            received_at timestamptz NOT NULL,
            verified_at timestamptz,
            payload_hash varchar(64) NOT NULL CHECK (payload_hash ~ '^[0-9a-f]{64}$'),
            CONSTRAINT uq_commerce_provider_transaction UNIQUE (
                provider, external_transaction_id
            )
        );
        CREATE INDEX ix_commerce_user_received
            ON commerce_evidence (user_id, received_at DESC);

        CREATE TABLE saved_selections (
            saved_selection_id varchar(36) PRIMARY KEY,
            user_id varchar(36) NOT NULL REFERENCES app_users (user_id) ON DELETE RESTRICT,
            match_id bigint NOT NULL REFERENCES matches (match_id) ON DELETE RESTRICT,
            prediction_snapshot_id bigint REFERENCES prediction_snapshots
                (prediction_snapshot_id) ON DELETE RESTRICT,
            market text NOT NULL CHECK (length(btrim(market)) > 0),
            selection text NOT NULL CHECK (length(btrim(selection)) > 0),
            line numeric,
            saved_decimal_odds numeric CHECK (saved_decimal_odds IS NULL OR saved_decimal_odds > 1),
            stake numeric CHECK (stake IS NULL OR stake > 0),
            currency varchar(3),
            tracking_status text NOT NULL DEFAULT 'ACTIVE' CHECK (
                tracking_status IN ('ACTIVE', 'SETTLED', 'REMOVED', 'REVIEW_REQUIRED')
            ),
            outcome text CHECK (outcome IS NULL OR outcome IN ('WON', 'LOST', 'VOID', 'WITHDRAWN')),
            created_at timestamptz NOT NULL,
            removed_at timestamptz,
            settled_at timestamptz,
            result_fingerprint varchar(64) CHECK (
                result_fingerprint IS NULL OR result_fingerprint ~ '^[0-9a-f]{64}$'
            ),
            CONSTRAINT ck_saved_stake_currency CHECK (
                (stake IS NULL AND currency IS NULL) OR (stake IS NOT NULL AND currency IS NOT NULL)
            ),
            CONSTRAINT ck_saved_tracking_shape CHECK (
                (tracking_status = 'ACTIVE' AND outcome IS NULL AND removed_at IS NULL)
                OR (tracking_status = 'REMOVED' AND outcome IS NULL AND removed_at IS NOT NULL)
                OR (tracking_status = 'SETTLED' AND outcome IS NOT NULL AND settled_at IS NOT NULL)
                OR (tracking_status = 'REVIEW_REQUIRED' AND outcome IS NOT NULL)
            )
        );
        CREATE UNIQUE INDEX uq_saved_selection_active_identity
            ON saved_selections (user_id, match_id, market, selection, COALESCE(line, -999))
            WHERE tracking_status = 'ACTIVE';
        CREATE INDEX ix_saved_selection_user_status
            ON saved_selections (user_id, tracking_status, created_at DESC);

        COMMENT ON TABLE app_users IS
            'Product identity only; canonical prediction computation remains global';
        COMMENT ON TABLE saved_selections IS
            'User-owned references to canonical evidence; never rewrites prediction history';
        """
    )


def downgrade() -> None:
    """Remove only provider-neutral product-service persistence."""
    op.execute(
        """
        DROP TABLE saved_selections;
        DROP TABLE commerce_evidence;
        DROP TABLE entitlement_evidence;
        DROP TABLE auth_sessions;
        DROP TABLE auth_identities;
        DROP TABLE app_users;
        """
    )
