"""followed_matches_and_push_tokens

Revision ID: 9c7c56a20a35
Revises: 4633ed520904
Create Date: 2026-09-29 00:01:33.260603
"""

from collections.abc import Sequence

from alembic import op

revision: str = "9c7c56a20a35"
down_revision: str | None = "4633ed520904"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE followed_matches (
            followed_match_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id varchar(36) NOT NULL REFERENCES app_users (user_id) ON DELETE RESTRICT,
            match_id bigint NOT NULL REFERENCES matches (match_id) ON DELETE RESTRICT,
            created_at timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT uq_followed_matches_user_match UNIQUE (user_id, match_id)
        );

        CREATE TABLE push_tokens (
            push_token_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id varchar(36) REFERENCES app_users (user_id) ON DELETE RESTRICT,
            provider text NOT NULL CHECK (provider = 'EXPO'),
            token text NOT NULL,
            created_at timestamptz NOT NULL DEFAULT now(),
            last_seen_at timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT uq_push_tokens_provider_token UNIQUE (provider, token)
        );

        CREATE INDEX ix_push_tokens_user_id ON push_tokens (user_id);
        """
    )


def downgrade() -> None:
    op.execute(
        """
        DROP TABLE push_tokens;
        DROP TABLE followed_matches;
        """
    )
